name: ekl-logging

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
    volumes:
      - ./infra/loki:/etc/loki

  promtail:
    image: grafana/promtail:latest
    ports:
      - "1514:1514"
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
    volumes:
      - /var/log:/var/log
      - ./infra/promtail:/etc/promtail

  grafana:
    image: grafana/grafana:latest
    user: "1000"
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki
    volumes:
    - ./infra/grafana:/var/lib/grafana

networks:
  loki:
    driver: bridge

configs:
  loki-config:
    file: ./infra/loki/loki-config.yml
  promtail-config:
    file: ./infra/promtail/promtail-config.yml